# Generated by Django 4.1.4 on 2023-01-05 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_tasks_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Tasklist',
        ),
    ]
